spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ABCDEFGHIJK01234567890
      
---
spring:
  profiles: test  datasource:    url: jdbc:h2:mem:test

